### ISSUE TITLE
Do not change the formatting of the original GitHub pull request description

### ISSUE THREAD

**Issue by shauke** [danhellem/github-actions-pr-to-work-item#18]
Once the "Sync GitHub Pull Requests to Azure DevOps" action runs on a pull request an `AB#1234` reference is added to the end of the description and with that the original Markdown formatting of the pull request is messed up in GitHub. The original Markdown formatting should be kept.

See this PR for an example: https://github.com/intershop/intershop-pwa/pull/777

![image](https://user-images.githubusercontent.com/50741106/124953202-369b1400-e015-11eb-9c61-a378bdbc64da.png)

### Original Message
![image](https://user-images.githubusercontent.com/50741106/124953309-52061f00-e015-11eb-9b22-62427425a47a.png)

### Changes after the Action (the formatting changes happen here)

![image](https://user-images.githubusercontent.com/50741106/124953490-7e21a000-e015-11eb-8cf7-2d23389de5a7.png)

### Just adding the link

![image](https://user-images.githubusercontent.com/50741106/124953686-a6a99a00-e015-11eb-97e6-0f520d2c5f77.png)

**Comment by danhellem** [comment]
ADO does not support markdown :(

**Comment by shauke** [comment]
The problem is not in ADO. The problem is in GitHub when adding the `AD#6474` ADO reference the whole description is changed. Basically all line breaks are replaced by `<br />`. The same works well in your Issue sync Action. It would be nice if the Pull Request sync Action would behave the same.

The "Changes after the Action" changes should look more like that:
![image](https://user-images.githubusercontent.com/50741106/125975151-8ec32a27-8f1f-435c-a3fc-ec8c10c509fd.png)

**Comment by danhellem** [comment]
I will take a look. But feel free to create a PR :)

**Comment by shauke** [comment]
Creating a PR is unfortunately something else then finding something is not working as expected.
The PR would be the next level. 😉

**Comment by MaxKless** [comment]
Hi @danhellem, I was just about to check in on this PR and see if I can solve it myself when I saw you put an "up next" label on it. Do you have a fix for this in the works?

Looking at the code, it seems like the issue stems from this line in `main.ts`
[`  payload.body = (request_body !== null) ? request_body.replace(new RegExp('\\r?\\n','g'), '<br />') : ''`](https://github.com/danhellem/github-actions-pr-to-work-item/blob/master/src/main.ts#L63)

Can you explain the motivation behind this? Because it would probably fix the issue to remove it but you also must've had a reason for implementing it this way :D

**Comment by danhellem** [comment]
@MaxKless yeah stand by actually. This was to put in to handle line breaks and replace them with <br> html. But I have a library i am going to use that converts the markdown to clean html. it is working great with my other action and i am about to add it to this action.

**Comment by danhellem** [comment]
Fixed in #28

**Comment by shauke** [comment]
@danhellem this seems to work very well now. Thanks a lot. 👍
